services:
  mysql:
    container_name: mysql_cn
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - spring-network  # Ensure MySQL is part of the network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_cn
      PMA_PORT: 3306
    ports:
      - "7098:80"
    networks:
      - spring-network  # Ensure phpMyAdmin is part of the same network

  mail-dev:
    container_name: mail-dev-bs
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  keycloak:
    container_name: keycloak-bs
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-network
    command:
      - "start-dev"

networks:
  spring-network:
    driver: bridge  # Network definition (optional but recommended for isolation)

volumes:
  mysql:
    driver: local  # Volume definition for MySQL data persistence
